### ISSUE TITLE
投稿詳細: コメント投稿後にコメント欄記入欄を空欄に戻す

### ISSUE THREAD

**Issue by chatagiri** [sksk000/Travelog#121]
- コメント投稿後に入力欄にコメントが残っている
![image](https://github.com/user-attachments/assets/c62f6c18-1af3-4d93-9b60-03182717808b)

**Comment by sksk000** [comment]
以下のプルリクエストにて、実装が織り込まれています。
https://github.com/sksk000/Travelog/pull/145
