### ISSUE TITLE
ユーザ詳細情報: 訪れた場所一覧を開いた時のマップの倍率を下げる

### ISSUE THREAD

**Issue by chatagiri** [sksk000/Travelog#129]
- 1つ目のピンの位置が基準になっていると思われる。
![image](https://github.com/user-attachments/assets/657f5a2e-7b10-4221-ae50-3f03283f5a8e)

- 全国旅した人の情報にアクセスしにくいため、ページを開いた時点で日本全土を写すようにする。

![image](https://github.com/user-attachments/assets/0d8238b7-b9c2-448e-b9f1-2c7a89bb54d4)

**Comment by sksk000** [comment]
以下プルリクエストの新規投稿・投稿編集時のマップの拡大率調整対応にて、同時に上記issueも対応
https://github.com/sksk000/Travelog/pull/146
